#!/usr/bin/env python3
"""Build project.js from src/*.js, in filename order.

Paste project.js into Xerte: Project > Optional properties > Script. Edit src/, never project.js.
Run: python3 build-project.py
"""
from pathlib import Path

HERE = Path(__file__).parent
BANNER = "/* Assessment Menu project script. Generated by build-project.py from src/*.js; edit those, not this file. */\n"

parts = sorted((HERE / "src").glob("*.js"))
(HERE / "project.js").write_text(BANNER + "\n".join(p.read_text() for p in parts))
print(f"wrote {HERE / 'project.js'} from {', '.join(p.name for p in parts)}")
