#!/usr/bin/env python3
"""Generate scss/_cu-tokens.scss from tokens/tokens.json.

tokens.json is the theme's own source of truth for its --cu-* design tokens. It was seeded from
the Cardiff Resource Design System and is maintained here, so the theme can differ from the
design system where Xerte needs it.

Format: each top-level key (other than $description) is a group with an optional $description
and tokens of the form {"$value": "...", "$description": "..."}. A value in braces, such as
{cu-white}, refers to another token and is written as var(--cu-white); the target must exist.

Usage (from the theme source folder):
    python3 tools/build-tokens.py            write the partial
    python3 tools/build-tokens.py --check    report only; exit 1 if the partial is out of date

Standard library only.
"""
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
THEME = HERE.parent  # theme-src/cardiffuniversity
SOURCE = THEME / "tokens" / "tokens.json"
TARGET = THEME / "scss" / "_cu-tokens.scss"
HEADER = (
    "// GENERATED by tools/build-tokens.py from tokens/tokens.json.\n"
    "// Do not edit: change tokens/tokens.json, then run tools/build-tokens.py (build.sh does it).\n"
)
ALIAS = re.compile(r"\{(cu-[\w-]+)\}")


def comment(text):
    return "/* " + text.replace("*/", "* /") + " */"


def render():
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    groups = {k: v for k, v in data.items() if not k.startswith("$")}
    names = [n for g in groups.values() for n in g if not n.startswith("$")]
    errors = [f"duplicate token: {n}" for n in sorted({n for n in names if names.count(n) > 1})]

    lines = []
    for key, group in groups.items():
        if lines:
            lines.append("")
        lines.append(" " + comment(group.get("$description", key)))
        for name, token in group.items():
            if name.startswith("$"):
                continue
            if not isinstance(token, dict) or "$value" not in token:
                errors.append(f"{key}.{name}: missing $value")
                continue
            value = str(token["$value"])
            for target in ALIAS.findall(value):
                if target not in names:
                    errors.append(f"{name}: refers to unknown token {{{target}}}")
            value = ALIAS.sub(r"var(--\1)", value)
            note = " " + comment(token["$description"]) if token.get("$description") else ""
            lines.append(f" --{name}:{value};{note}")

    if errors:
        sys.exit("ERROR in tokens/tokens.json:\n  " + "\n  ".join(errors))
    return HEADER + ":root {\n" + "\n".join(lines) + "\n}\n"


def main():
    fresh = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None
    if current == fresh:
        print(f"In sync: {TARGET.relative_to(THEME)} matches tokens/tokens.json.")
        return 0
    if "--check" in sys.argv[1:]:
        print(f"OUT OF DATE: {TARGET.relative_to(THEME)}. Run: python3 tools/build-tokens.py")
        return 1
    TARGET.write_text(fresh, encoding="utf-8")
    print(f"Updated: {TARGET.relative_to(THEME)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
